# Generated by Django 3.1.5 on 2021-01-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0005_auto_20210116_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='last_recent_year',
        ),
        migrations.AddField(
            model_name='tag',
            name='latest_crawled_year',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='tag',
            name='old_crawled_year',
            field=models.IntegerField(default=-1),
        ),
    ]
